### PR TITLE
Kyle/symco 95 Template Management changes

### PR DESCRIPTION
**Pull request by kaigoos**
Made changes to the functionality of template management page. 

Folder table:
- Search bar can search for all folders regardless of what is being shown in the table.
- Adding folders has been changed. There is an input box above the table that the user can type in a name of a folder which will create an empty folder. Duplicate names will result in an error message to pop up at the top of the screen below the navbar.
- The edit button now shows a modal just to edit the name of the folder, what templates are in the foldercannot be edited from here anymore.
- All templates button should be pinned to the top of the table and should always be regardless of search or pagination.

Template Table:
- Current folder name is now displayed above the table.
- Search bar only suggests templates that are in the folder.
- Adding templates to a folder has been changed. There is a multi-select input box above the table that lets the user select multiple templates that are not already in the folder. Upon selection the template names should be displayed within the input box. Press "add" button to add the selected templates to the folder.
- Multi-select box suggestions should show both the template name and creation date, but once selected it will only show the template name to avoid cluttering since already kind of cluttered anyways. Current date is shown since template names are not unique at the moment. 

Layout is janky so just ignore that for now

### CODE REVIEW

**Review by Likhovodov — APPROVED** [review]
Looks good!

Make sure to pip freeze into requirements.txt (django-select2) is not in the list.

Would it be possible to show the folders table with just 'All folders' if there are not folders (Instead of nothing). (And the templates folder with 'Nothing' if there are no templates)... just so the table is there... unless doing this is nontrivial... this is more of a nitpick.

**Comment by kaigoos** [comment]
> 
> 
> Looks good!
> 
> Make sure to pip freeze into requirements.txt (django-select2) is not in the list.
> 
> Would it be possible to show the folders table with just 'All folders' if there are not folders (Instead of nothing). (And the templates folder with 'Nothing' if there are no templates)... just so the table is there... unless doing this is nontrivial... this is more of a nitpick.

I actually didn't need to user django-select2 at all so I didn't put it into the requirements. I just use the link and script for the CDN in the html which is much easier than using django-select2 which required me to setup caching.
Showing all folders when there are none should be pretty easy so I will fix that!

**Comment by Likhovodov** [comment]
Hmm, django yelled at me for not having it installed  ¯\_(ツ)_/¯

**Comment by kaigoos** [comment]
> 
> 
> Hmm, django yelled at me for not having it installed ¯_(ツ)_/¯

Oh then I guess we do need it then. I'll add it in there

**Review by devin-w-hill — CHANGES_REQUESTED** [review]
really nice, easy to use.

**Review by devin-w-hill — APPROVED** [review]

**Pull request merged**
