### PR TITLE
Kyle/symco 34: Custom Response

### PR DESCRIPTION
**Pull request by kaigoos**
Made a text input one of the selectable options in the choices for a conversation. Conversation ends and the student is taken to the conversation end page after submitting a custom response as their choice. Submitting with an empty string when choosing the custom response will result in an error.

### CODE REVIEW

**Review by rosasck — DISMISSED** [review]
Works for me.... i think? if i click and unclick it it still says i pressed it... but this only happened once and i refreshed and seemed to be fine... i would love if people tested this and made sure it wasnt me

**Review by JerCarnahan — DISMISSED** [review]
Tested it all out and it seems to work! It broke once but I think that had to do with an invalid audio recording (my mic wasn't set up yet) and not the custom response.

**Review by ericharper1 — CHANGES_REQUESTED** [review]
Very solid stuff here, but I think we should do some front-end validation if the user selects custom response but doesn't put in text. Display an error and say that the text field needs to be filled. I say this because I got stuck when I selected the custom response without inputting text -- my back button disable functionality said "Nuh uh". Lol

**Review by Likhovodov — DISMISSED** [review]
Looks good

**Review by rosasck — DISMISSED** [review]
great job!

**Review by ericharper1 — DISMISSED** [review]
Works great!

**Comment by JerCarnahan** [comment]
Just gotta fix merge conflicts

**Review by rosasck — APPROVED** [review]

**Review by Likhovodov — APPROVED** [review]

**Review by ericharper1 — APPROVED** [review]

**Pull request merged**
