### PR TITLE
Change TemplateNode and added admindocs support

### PR DESCRIPTION
**Pull request by ericharper1**

### CODE REVIEW

**Comment by ericharper1** [comment]
Destroyed the last PR to try and fix all those file changes appearing under my PR... was too much of a headache. 

Everything here is the same as the last PR; however I changed the python version in the pipfile. Which I am not sure if we'll end up using that pipfile, at least with our current workflow.

**Review by Likhovodov — APPROVED** [review]
Looks good. My only concern is the pipfile. I'm down to transition to it. I wouldn't want both a pipfile and a requirement.txt though.

**Comment by ericharper1** [comment]
Yeah I also think the transition would be good. Each person would need to be using pipenv, because I think it's a pipenv thing. We can address this later maybe.

**Review by rosasck — APPROVED** [review]
Looks great! Only concern is same as David

**Pull request merged**
