### PR TITLE
Added transcription editing for students

### PR DESCRIPTION
**Pull request by JerCarnahan**
Was not able to test because DB is being funky. Basically students should be able to edit transcriptions until the researcher does. Then it's locked

### CODE REVIEW

**Review by rosasck — APPROVED** [review]

**Review by kaigoos — CHANGES_REQUESTED** [review]
I got locked out of editing a transcription soon as I updated it as a student.

**Comment by JerCarnahan** [comment]
> 
> 
> I got locked out of editing a transcription soon as I updated it as a student.

Fixed now

**Review by kaigoos — APPROVED** [review]
Works great!

**Review by Likhovodov — APPROVED** [review]
Looks good!

**Pull request merged**
