### PR TITLE
All of SYMCO-11, Django has a standard form for changing passwords

### PR DESCRIPTION
**Pull request by JerCarnahan**
Symco-11, For changing user password. Django has a premade form for this

### CODE REVIEW

**Review by rosasck — APPROVED** [review]

**Review by kaigoos — DISMISSED** [review]

**Review by ericharper1 — DISMISSED** [review]

**Review by Likhovodov — DISMISSED** [review]

**Review by rosasck — DISMISSED** [review]
we now have two settings pages! look at my PR

**Review by rosasck — CHANGES_REQUESTED** [review]
Just to make sure the nav bar isn't broken incase you have different URLS and stuff, lets merge mine in first and then yours

**Comment by rosasck** [comment]
but it looks good

**Review by rosasck — CHANGES_REQUESTED** [review]
fix the merge conflicts and then i can approve

**Comment by rosasck** [comment]
Lets get this merged :)

**Review by rosasck — CHANGES_REQUESTED** [review]
fix merge conlflicts plzzzzzzzzzz

**Pull request closed without merging**
