### PR TITLE
Devin/symco 40, 43, 44

### PR DESCRIPTION
**Pull request by devin-w-hill**
Students can see feedback for any responses they've submitted. Ratings for those are displayed in modal. Attempts left count is displayed in django_table.

To test: Assign a template to two students. Log in as one and do template. It should update their retry count and move the template to the bottom table on home page. View feedback using button and select response to view. It should take you to the view_feedback page. Doing same template twice should show two options in modal to view. Logging in as second student should show full attempt count and template should be in top table.

CSS on view_feedback page is whack. Retry attempts aren't enforced yet. Moved view_response.py under conversation_templates app since it makes more sense over there. Made some other small changes to satisfy linter/eyes.

### CODE REVIEW

**Review by ericharper1 — COMMENTED** [review]
Tested and everything is working the way it's supposed to. Can I request that each table on the student home page have some title name? Because at first glance when no conversations are completed, it looks like the empty table at the bottom of the page shouldn't be there

**Comment by devin-w-hill** [comment]
> Tested and everything is working the way it's supposed to. Can I request that each table on the student home page have some title name? Because at first glance when no conversations are completed, it looks like the empty table at the bottom of the page shouldn't be there

Good idea, I will give them titles

**Comment by devin-w-hill** [comment]
Need to figure out pagination for modals before merging. Pagination on django tables doesn't work inside a modal.

**Comment by devin-w-hill** [comment]
Ok ready to go.

**Review by ericharper1 — APPROVED** [review]
Cash money. 

Holding a poll:
Do you think there should be column for 'attempts' in the Completed Table?

Thumbs up if yes, thumbs down if Eric sucks.

**Review by rosasck — APPROVED** [review]

**Comment by devin-w-hill** [comment]
> Cash money.
> 
> Holding a poll:
> Do you think there should be column for 'attempts' in the Completed Table?
> 
> Thumbs up if yes, thumbs down if Eric sucks.

What's funny about your poll is that both thumbs up and thumbs down mean that we keep the attempts column hahaha

**Pull request merged**
