### PR TITLE
SYMCO-17

### PR DESCRIPTION
**Pull request by xingjianW**
This branch is consistent with Xingjian/SYMCO-17, but there is no complicated history.

### CODE REVIEW

**Review by ericharper1 — DISMISSED** [review]
Everything still runs as expected! One thing I did notice is that using labels doesn't work. It looks like the issue is line 137 in create_assignment.py. We should be querying by the id instead of by name.

Screen Shot 2021-02-21 at 03 06 33

**Comment by Likhovodov** [comment]
So, one researcher can not have labels with identical names. However, two researchers can have labels with the same name between each-other. So the query on line 137 has to query by label name only from that individual researcher's labels (not all labels)

**Review by devin-w-hill — APPROVED** [review]
Everything looks good to me

**Review by Likhovodov — APPROVED** [review]
This is ready to go. Don't forget to squash merge

**Pull request merged**
