### PR TITLE
Added Read receipts on feedback

### PR DESCRIPTION
**Pull request by JerCarnahan**
Should be pretty simple to test. Changing feedback sets it to false while viewing the feedback as a student should make it true

### CODE REVIEW

**Review by kaigoos — COMMENTED** [review]
I'm not sure if this ticket is related to it bu the view response in the student home page isn't working form me. Looks like a modal is suppose to pop up, but I'm not seeing anything.

**Comment by JerCarnahan** [comment]
> 
> 
> I'm not sure if this ticket is related to it bu the view response in the student home page isn't working form me. Looks like a modal is suppose to pop up, but I'm not seeing anything.

Nothing to do with me, it's a bug in main and there's already a ticket

**Comment by rosasck** [comment]
Is it just a wierd state bug with the new main.. but i dont see anything to indicate to the user that they have new feedback..

**Comment by Likhovodov** [comment]
Idk if the ticket describes this well (I did not find another ticket either), but I think this ticket also encompasses displaying the feedback button differently if feedback flag is set.

**Review by kaigoos — APPROVED** [review]

**Review by rosasck — APPROVED** [review]

**Pull request merged**
